### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lavdnone** [techno-express/freepbx#1]
regardless of the run settings, circles with below errors
docker version | grep Version
 Version:      17.11.0-ce
 Version:      17.11.0-ce

> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> Starting sshd: G[  OK  ]
> 2017-12-01 19:22:17,898 fail2ban.server         [599]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:22:17,898 fail2ban.server         [599]: INFO    Starting in daemon mode
> ERROR:systemctl:the service is already running on PID 622
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:22:29,825 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:22:29,825 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:22:41,050 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:22:41,050 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:24:49,309 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:24:49,309 fail2ban.server         [566]: INFO    Starting in daemon mode
> ERROR:systemctl:the service is already running on PID 640
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:24:59,773 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:24:59,773 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:29:05,340 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:29:05,340 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:31:13,786 fail2ban.server         [567]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:31:13,787 fail2ban.server         [567]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:33:22,218 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:33:22,218 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:35:30,575 fail2ban.server         [565]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:35:30,575 fail2ban.server         [565]: INFO    Starting in daemon mode
> ERROR:systemctl:the service is already running on PID 640
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:35:39,956 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:35:39,956 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:39:45,655 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:39:45,655 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:43:51,356 fail2ban.server         [565]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:43:51,356 fail2ban.server         [565]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:45:59,900 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:45:59,900 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:48:08,368 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:48:08,368 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:52:14,014 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:52:14,014 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 19:56:20,566 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 19:56:20,566 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 20:00:26,113 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 20:00:26,113 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 20:02:34,378 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 20:02:34,378 fail2ban.server         [566]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 20:04:42,807 fail2ban.server         [568]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 20:04:42,807 fail2ban.server         [568]: INFO    Starting in daemon mode
> Traceback (most recent call last):
>   File "/usr/bin/systemctl", line 3162, in <module>
>     result = command_func()
>   File "/usr/bin/systemctl", line 2807, in system_default
>     self.start_system_default(init = init)
>   File "/usr/bin/systemctl", line 2814, in start_system_default
>     self.start_units(default_services)
>   File "/usr/bin/systemctl", line 1280, in start_units
>     if not self.start_unit(unit):
>   File "/usr/bin/systemctl", line 1295, in start_unit
>     return self.start_unit_from(conf)
>   File "/usr/bin/systemctl", line 1317, in start_unit_from
>     run = subprocess_wait(sudo+newcmd, env)
>   File "/usr/bin/systemctl", line 410, in subprocess_wait
>     run = subprocess.Popen(cmd, shell=shell, env=env)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
> If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
> 2017-12-01 20:06:51,283 fail2ban.server         [566]: INFO    Starting Fail2ban v0.9.7
> 2017-12-01 20:06:51,283 fail2ban.server         [566]: INFO    Starting in daemon mode

**Comment by TheTechsTech** [comment]
Sorry for the delayed reply. I got that same error, the original systemd service was still loading units that i thought i had removed from startup. Any service using dbus inside docker has issues running. The solution from https://github.com/gdraheim/docker-systemctl-replacement solves that issue i'm using here. 

The current build should be fine, I believe i got most those problems out. About a month ago, I had accidentally stop and deleted my image and data volumes, and on restart i got that same error initially. I didn't realize issues because I was using as my daily driver an old build and not the one posted that i'm updating.

**Comment by TheTechsTech** [comment]
Just updated the image to centos 7.8, freepbx 15 and asterisk 16.
