### ISSUE TITLE
Please help, followed readme, docker container is up and running but cannot access at IP:9000

### ISSUE THREAD

**Issue by Jieiku** [techno-express/freepbx#2]
I figured this out, I will document the things I noticed, but primarily to make use of the ports that are defined with EXPOSE in the Dockerfile you have to use -P in your run command, otherwise the webui cannot be accessed, and the default readme lists it as being at port 9000 but its actually port 9990

This Got me up and running:
```
docker run -P --name freepbx \
-v freepbx-etc:/etc \
-v freepbx-www:/var/www \
-v freepbx-log:/var/log \
-v freepbx-lib:/var/lib \
-v freepbx-home:/home \
-v /etc/resolv.conf:/etc/resolv.conf:ro \
--cap-add=NET_ADMIN --net=host \
--hostname=freepbx.example.com \
--restart=always -itd technoexpress/freepbx
```
https://IPADDRESS:9990
default login is: root / freepbx

Also if using -P to allow the webui to be accessed is a bad way of doing it, please let me know the better way, im still new to using docker.

**Comment by xekon** [comment]
adding -P makes it make use of the EXPOSE directive.

I am now able to access the webui, I found another GOTCHA though.

The Helpfile/Readme lists Using the Webmin UI visit https://ip_or_hostname:9000

but the Dockerfile is actually using 9990

**Comment by Jieiku** [comment]
Now I can see after bashing into the container that some ports are listening on 0.0.0.0 and others are listening on 127.0.0.1

I have an external nginx server that is already making use of ports 80 and 443, so I think I need to have the docker container listen on 127.0.0.1 instead of 0.0.0.0 for ports 80 and 443, and use my external nginx to proxy pass to the container..... I just need to figure out how to do it. One of the other docker project I use does this, but I simply had to set it as such in the config file they provide.

Time for more reading and searching google.

**Comment by TheTechsTech** [comment]
> Also if using -P to allow the webui to be accessed is a bad way of doing it, please let me know the better way, im still new to using docker.

Just updated the image to centos 7.8, freepbx 15 and asterisk 16.

Usinp -P is bad, i'm using by `--ip=111.222.333.446` taking control of the public ip, so the ports are under firewall control, only a few open, other blocked by default. 

> I have an external nginx server that is already making use of ports 80 and 443, so I think I need to have the docker container listen on 127.0.0.1 instead of 0.0.0.0 for ports 80 and 443

You need to setup a proxy, and use a different domain name, that is how i have it setup.
