### ISSUE TITLE
No CDR reports

### ISSUE THREAD

**Issue by jeffgoh** [techno-express/freepbx#3]
full:[2019-02-25 08:00:43] WARNING[23746] res_odbc.c: res_odbc: Error SQLConnect=-1 errno=0 [unixODBC][Driver Manager]Can't open lib 'libmyodbc.so' : file not found
full:[2019-02-25 08:00:43] NOTICE[23746] res_odbc.c: Registered ODBC class 'asteriskcdrdb' dsn->[MySQL-asteriskcdrdb]

**Comment by TheTechsTech** [comment]
Just updated the image to centos 7.8, freepbx 15 and asterisk 16. Should be working now.
