### ISSUE TITLE
I can't login from webmin

### ISSUE THREAD

**Issue by hacarrillom** [techno-express/freepbx#4]
Hello everybody, that's my firs post on GitHub.

Please I need support, I installed this container and everything is fine, I can open the webadmin, but when I enter the username (admin) and password (issabel-4) I get a message that says: "Warning! Login failed. Please try again. ".

If someone has the same problem or someone has the solution, I would really appreciate it.

**Comment by TheTechsTech** [comment]
The login to _Webmin_ is the standard **root** for _username_, and the _password_ is **freepbx**

You on the wrong repo, Issabel-PBX is at https://github.com/techno-express/Issabel-PBX.

**Comment by hacarrillom** [comment]
Oh, thank you! I gonna try it!

**Comment by hectorkrrillo** [comment]
I don't know what I'm doing wrong, but the container run well, but when I wrote root and freepbx I received the same message.

Check the attachment files please.

Later I checked and try to modify that: 

**asterisk.issabel/manager.conf**

[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038
#include manager_general_additional.conf

[admin]
secret = AMPMGRPASS
deny=192.168.0.1/255.255.255.0
permit=10.0.0.143/0.0.0.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

**asterisk/manager.conf**

[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038
#include manager_general_additional.conf

[admin]
secret = issabel-4
deny=192.168.0.1/255.255.255.0
permit=10.0.0.143/0.0.0.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

But I got the same issues results 😞

**Comment by hectorkrrillo** [comment]
Hello @techno-express thank you for your answer
![Captura de Pantalla 2020-09-24 a la(s) 12 00 15](https://user-images.githubusercontent.com/71658857/94176859-51bdde00-fe5e-11ea-89a5-02fa7ea9eb1a.png)
![Captura de Pantalla 2020-09-24 a la(s) 12 00 32](https://user-images.githubusercontent.com/71658857/94176862-52ef0b00-fe5e-11ea-8057-f99607bbc24f.png)



I don't know what I'm doing wrong, but the container run well, but when I wrote root and freepbx I received the same message.

**Check the attachment files please.**

Later I checked and try to modify that:

**asterisk.issabel/manager.conf**

[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038
#include manager_general_additional.conf

[admin]
secret = AMPMGRPASS
deny=192.168.0.1/255.255.255.0
permit=10.0.0.143/0.0.0.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

**asterisk/manager.conf**

[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038
#include manager_general_additional.conf

[admin]
secret = issabel-4
deny=192.168.0.1/255.255.255.0
permit=10.0.0.143/0.0.0.0
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000

But I got the same issues results 😞

**Comment by TheTechsTech** [comment]
That is for this **repo** only!!!
